atexpand: add @VERSION@, help information.

diff --git a/scripts/atexpand.in b/scripts/atexpand.in
--- a/scripts/atexpand.in
+++ b/scripts/atexpand.in
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+VERSION=@VERSION@
+
 ##
 ## Helper script to automatically view a tabular file
 ## with properly tabulated fields.
@@ -9,10 +11,29 @@
 ## License: AGPLv3 or later
 
 FILE=$1
-if [ -z "$FILE" ] ; then
-	echo "Error: missing file name to view. See 'detect_tab_stops --help' for help." >&2
-	exit 1
+if [ -z "$FILE" -o "$1" = "-h" -o "$1" = "--help" ]; then
+	BASE=$(basename $0)
+	echo "
+atexpand - Print a file, with automatic tab expantion
+Version: $VERSION
+
+Copyright (C) 2012, A. Gordon ( gordon at cshl dot edu )
+License: AGPLv3+
+
+Usage:
+  $BASE [INPUT-FILE]
+
+Will read INPUT-FILE, and output (to STDOUT) the file,
+after expanding TABS to spaces, ensuring adequete spaces are
+inserted to align all fields properly (uses 'detect_Tab_stops'
+to calculate tab expansion).
+
+"
+
+    exit
 fi
+
 [ -e "$FILE" ] || { echo "Error: file '$FILE' not found." >&2 ; exit 1 ; }
+[ -r "$FILE" ] || { echo "Error: Input file must be a regular file (not a pipe/socket)" >&2 ; exit 1 ; }
 
 expand -t$(detect_tab_stops "$FILE") "$FILE"
