maint: improve scripts with 'usage()' and 'die()' functions

diff --git a/scripts/atexpand.in b/scripts/atexpand.in
--- a/scripts/atexpand.in
+++ b/scripts/atexpand.in
@@ -1,15 +1,21 @@
 #!/bin/sh
 
-##
 ## Helper script to automatically view a tabular file
 ## with properly tabulated fields.
 ## See "detect_tab_stops --help" for details.
 ##
-## Copyright (C) 2012   A. Gordon (gordon at cshl dot edu)
+## Copyright (C) 2012,2014  A. Gordon (gordon at cshl dot edu)
 ## License: @LICENSE@
 
-FILE=$1
-if [ -z "$FILE" -o "$1" = "-h" -o "$1" = "--help" ]; then
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 atexpand - Print a file, with automatic tab expantion
@@ -31,11 +37,15 @@ Equivalent to:
 while automatically calculating N1,N2,N3,N4 for optimal viewing.
 
 "
-
     exit
-fi
+}
 
-[ -e "$FILE" ] || { echo "Error: file '$FILE' not found." >&2 ; exit 1 ; }
-[ -r "$FILE" ] || { echo "Error: Input file must be a regular file (not a pipe/socket)" >&2 ; exit 1 ; }
+FILE=$1
+test -z "$FILE" && die "Missing input file name. See --help for details."
+test "x$1" = "x-h" || test "x$1" = "--help" && usage
 
-expand -t$(detect_tab_stops "$FILE") "$FILE"
+test -e "$FILE" || die "file '$FILE' not found."
+test -r "$FILE" || die "Input file must be a regular file (not a pipe/socket)"
+
+expand -t$(detect_tab_stops "$FILE") -- "$FILE" \
+    || die "expand failed on '$FILE'"
diff --git a/scripts/atless.in b/scripts/atless.in
--- a/scripts/atless.in
+++ b/scripts/atless.in
@@ -8,8 +8,15 @@
 ## Copyright (C) 2012   A. Gordon (gordon at cshl dot edu)
 ## License: @LICENSE@
 
-FILE=$1
-if [ -z "$FILE" -o "$1" = "-h" -o "$1" = "--help" ]; then
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 atless - view a file (using 'less'), with automatic tab expantion
@@ -31,11 +38,14 @@ Equivalent to:
 while automatically calculating N1,N2,N3,N4 for optimal viewing.
 
 "
-
     exit
-fi
+}
 
-[ -e "$FILE" ] || { echo "Error: file '$FILE' not found." >&2 ; exit 1 ; }
-[ -r "$FILE" ] || { echo "Error: Input file must be a regular file (not a pipe/socket)" >&2 ; exit 1 ; }
+FILE=$1
+test -z "$FILE" && die "Missing input file name. See --help for details."
+test "x$1" = "x-h" || test "x$1" = "--help" && usage
 
-less -S -x$(detect_tab_stops "$FILE") "$FILE"
+test -e "$FILE" || die "file '$FILE' not found."
+test -r "$FILE" || die "Input file must be a regular file (not a pipe/socket)"
+
+less -S -x$(detect_tab_stops "$FILE") -- "$FILE"
diff --git a/scripts/filetype_size_breakdown.in b/scripts/filetype_size_breakdown.in
--- a/scripts/filetype_size_breakdown.in
+++ b/scripts/filetype_size_breakdown.in
@@ -1,10 +1,24 @@
 #!/bin/sh
 
 ##
-## This script calculates how much disk space is used by each file type (e.g. "txt", "fq")
+## Copyright (C) 2012   A. Gordon (gordon at cshl dot edu)
+## License: @LICENSE@
 ##
 
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
+##
+## This script calculates how much disk space is used by each file type \
+## (e.g. "txt", "fq")
+##
+
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 filetype_size_breakdown - Summarize disk-usage by file type.
@@ -30,14 +44,16 @@ Example:
  log	379
 
 "
-
     exit
-fi
+}
 
 SRC=$1
-[ -z "$SRC" -o -d "$SRC" ] || { echo "Error: '$SRC' is not a valid directory'" >&2 ; exit 1 ; }
+test -z "$SRC" && die "Missing directory name. See --help for details."
+test "x$1" = "x-h" || test "x$1" = "--help" && usage
 
-find $SRC -type f -printf "%f\t%s\n" |
+test -d "$SRC" || die "'$SRC' is not a valid directory."
+
+find -- "$SRC" -type f -printf "%f\t%s\n" |
 	awk -v OFS="\t" -v FS="\t" '$1~/\./ { gsub(/.*\./,"",$1); print $1, $2 ; next }
 	     { print "[no_extension]", $2 }' |
 	sort -k1V,1 |
diff --git a/scripts/make_balloon.in b/scripts/make_balloon.in
--- a/scripts/make_balloon.in
+++ b/scripts/make_balloon.in
@@ -1,11 +1,21 @@
 #!/bin/sh
 
+## Copyright (C) 2012,2014   A. Gordon (gordon at cshl dot edu)
+## License: @LICENSE@
+
 ##
 ## creates a big empty/sparse file named "balloon_X"
 ##
 
-SIZE=$1
-if [ -z "$SIZE" -o "$1" = "-h" -o "$1" = "--help" ]; then
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 Make-Ballon - create big empty files in the current directory.
@@ -26,12 +36,19 @@ Note:
   (e.g. balloon_1, balloon_2, balloon_3 ... balloon_51 ...
 
 "
-
     exit
-fi
+}
+
+SIZE=$1
+test -z "$SIZE" && die "missing SIZE parameter. See --help for detauls"
+test "x$1" = "x-h" || test "x$1" = "--help" && usage
+
+echo "$SIZE" | grep -qE "^[0-9]+(K|KB|M|MB|G|GB|)?$" \
+    || die "invalid size '$SIZE'. See --help for details"
 
 ## find any existing ballons, create the next one
-LAST_BALLOON=$(ls balloon* 2>/dev/null | sed -r 's/balloon_?//' | sort -n | tail -n 1)
+LAST_BALLOON=$(ls balloon* 2>/dev/null \
+               | sed -r 's/balloon_?//' | sort -n | tail -n 1)
 if [ -z "$LAST_BALLOON" ]; then
 	BALLOON=1
 else
