auto-build-install: skip ./configure if file is missing.

diff --git a/scripts/auto-build-install.in b/scripts/auto-build-install.in
--- a/scripts/auto-build-install.in
+++ b/scripts/auto-build-install.in
@@ -257,8 +257,10 @@ fi
 ##
 ## Configure
 ##
-./configure $configure_params \
-    || die "./configure failed"
+if test -e "./configure" ; then
+    ./configure $configure_params \
+        || die "./configure failed"
+fi
 
 ##
 ## Make
