psx: major rewrite.
Add @VERSION@, help screen,
make abs-path resolving portable.

diff --git a/scripts/psx.in b/scripts/psx.in
--- a/scripts/psx.in
+++ b/scripts/psx.in
@@ -1,13 +1,51 @@
 #!/bin/sh
 
-# No parameter: copy current directory to clipboard
-if [ -z "$1" ]; then
-	echo -n $PWD | xsel -b
-	exit
+VERSION=@VERSION@
+
+if [ "$1" = "-h" -o "$1" = "--help" ]; then
+	BASE=$(basename $0)
+	echo "
+ppsx - Copy full path of file/dir name to clipboard
+Version: $VERSION
+
+Copyright (C) 2012, A. Gordon ( gordon at cshl dot edu )
+License: AGPLv3+
+
+Usage:
+  $BASE
+  $BASE [FILE-or-DIRECTORY]
+
+Will copy the full path of the specified file/directory (or current directory)
+to the clipboard.
+
+Then it can be easily pasted into a command line.
+
+Example:
+  $BASE myfile.txt
+
+  Assuming the current directory is '/home/bob/documents/',
+  The program will copy the following string into the clipboard:
+     /home/bob/documents/myfile.txt
+
+Note:
+1. Requires 'xsel' program to be installed
+2. Requires a valid X11-forwarding setting
+
+"
+
+    exit
 fi
 
-[ -e "$1" ] || { echo "File '$1' not found!" >&2 ; exit 1 ; }
 
-FULLPATH=$(readlink -n -f "$1")
+if [ -z "$1" ]; then
+	# No parameter: copy current directory to clipboard
+	FULLPATH=$PWD
+else
+	# Got a command-line parameter: assume it's a file name
+	[ -e "$1" ] || { echo "File '$1' not found!" >&2 ; exit 1 ; }
 
-echo -n "$FULLPATH" | xsel -b
+	# Resolve the absolute path in a portable way
+	FULLPATH=$(perl -MCwd -e '$f=Cwd::realpath($ARGV[0]); die unless -e $f; print $f' "$1") || exit 1;
+fi
+
+printf "$FULLPATH" | xsel -b
