scripts: improve usage() function

diff --git a/scripts/sum_file_sizes.in b/scripts/sum_file_sizes.in
--- a/scripts/sum_file_sizes.in
+++ b/scripts/sum_file_sizes.in
@@ -9,7 +9,15 @@ License: GPLv3+
 ## Prints the total size used by file types
 ##
 
-if [ -z "$1" -o "$1" = "-h" -o "$1" = "--help" ]; then
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 sum_file_sizes - Prints the total size of all specified files
@@ -28,8 +36,14 @@ NOTE:
 
 "
 	exit 0
-fi
+}
+
+test "x$1" = "x-h" || test "x$1" = "x--help" && usage
+test -z "$1" && die "missing file glob (e.g. '*.txt'). See --help for details."
 
 GLOB=$1
 
-find -iname "$GLOB" -printf "%s\n" | awk '{sum+=$1}END{print sum}' | human.py --div 1000 | sed 's/ //g'
+find -iname "$GLOB" -printf "%s\n" \
+    | awk '{sum+=$1}END{print sum}' \
+    | human.py --div 1000 \
+    | sed 's/ //g'
diff --git a/scripts/tardir.in b/scripts/tardir.in
--- a/scripts/tardir.in
+++ b/scripts/tardir.in
@@ -11,7 +11,16 @@ License: GPLv3+
 ## In the tarball, the files will be prefixed with a directory AND a time-stamp.
 ##
 
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
+die()
+{
+    BASE=$(basename -- "$0")
+    echo "$BASE: error: $@" >&2
+    exit 1
+}
+
+
+usage()
+{
 	BASE=$(basename $0)
 	echo "
 tardir - Packs the files in the current directory into a tar-ball.
@@ -45,13 +54,15 @@ with the following files:
 
 "
     exit
-fi
+}
+
+test "x$1" = "x-h" || test "x$1" = "x--help" && usage
 
 # Get the name of the current directory
-BASE=$(basename "$PWD") || exit
+BASE=$(basename -- "$PWD") || exit
 
 # Add time-stamp
-BASETIME=${BASE}_$(date +%F_%H%M%S) || exit
+BASETIME=${BASE}-$(date +%F-%H%M%S) || exit
 
 # Name of the final Tarball output file
 TARBALL=${BASETIME}.tar.bz2
